version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      # You can install dependencies here if needed
      - echo Installing dependencies...
  build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: .
